
####################################################################################
# Generated by Vivado 2020.2 built on 'Wed Nov 18 09:12:47 MST 2020' by 'xbuild'
# Command Used: write_xdc -force /uio/hume/student-u82/martimn/in3160/oblig6/constraints.xdc
####################################################################################


####################################################################################
# Constraints from file : 'constraints.xdc'
####################################################################################

set_property PACKAGE_PIN AB7 [get_ports {abcdefg_n[6]}]
set_property PACKAGE_PIN AB6 [get_ports {abcdefg_n[5]}]
set_property PACKAGE_PIN Y4 [get_ports {abcdefg_n[4]}]
set_property PACKAGE_PIN AA4 [get_ports {abcdefg_n[3]}]
set_property PACKAGE_PIN V7 [get_ports {abcdefg_n[2]}]
set_property PACKAGE_PIN W7 [get_ports {abcdefg_n[1]}]
set_property PACKAGE_PIN V5 [get_ports {abcdefg_n[0]}]
set_property PACKAGE_PIN V4 [get_ports c]
set_property PACKAGE_PIN Y9 [get_ports mclk]
set_property PACKAGE_PIN R18 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports {abcdefg_n[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefg_n[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefg_n[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefg_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefg_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefg_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefg_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports mclk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

create_clock -period 10.000 -waveform {0.000 5.000} [get_ports mclk]

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
